### ISSUE TITLE
Debug on Twitter API connection show a weird Wikipedia link?

### ISSUE THREAD

**Issue by cmceachern** [bcole808/wp-social-metrics-tracker#82]
Hello,

The connection to Twitter API is coming back with a 404 code. When I look at the debugger I see a weird wikipedia link appended on the Twitter request uri. Do you know how I can fix this? I looked at the php file and it doesn't include this weird link in the code. Here's what I am seeing in debugger:

Array
(
    [request_time] => 2015-11-25 12:00:07
    [request_method] => get
    [request_uri] => http://urls.api.twitter.com/1/urls/count.json?url=http%3A%2F%2Fwww.wikipedia.org
    [request_response] => Array

Thoughts? Solutions?

Thanks,

Claire

**Comment by bcole808** [comment]
Hello! 

The Twitter API is down because Twitter has officially removed it. You can read more on these threads:

https://wordpress.org/support/topic/will-twitters-changes-of-chare-counts-affect-smt
https://wordpress.org/support/topic/alternative-counter-for-disabled-twitter-api

The Wikipedia URL is a generic test URL that this plugin uses when it needs to try to reconnect to an API when there are errors. 

I need to update the plugin to remove the Twitter API since it is no longer available from Twitter.

**Comment by bcole808** [comment]
Twitter is now removed in version 1.6.3: https://github.com/chapmanu/wp-social-metrics-tracker/releases/tag/v1.6.3

**Comment by jonathantneal** [comment]
As always, you are doing a really fine job maintaining this project. Sad to see Twitter go. Glad to see the project work beyond that.

**Comment by bcole808** [comment]
Thanks! I hope that one day there will be another endpoint that provides the Twitter data, either directly from Twitter or from a third party source... I'll be waiting to see what the internet comes up with.
